print("Here's my day so far:")
print("Went to jail,")
print("lost the girl of my dreams,")
print("and got my butt kicked pretty good.")
print("Still, things could be worse.")
print("Oh, that's right.")
print("I'm falling to my death.")
print("Guess they can't")
print("How'd it all come to this, you ask?")
print("My end starts at the beginning")