man = input("Please enter a name ")
walks = input("Enter a verb ending in s ")
quantity = input("Enter a number")
food = input("Please enter a food ")
manSus = input("Enter the name of someone suspicious ") 
describer = input("Enter a silly adjective ")
manFriend = input("Enter a famous person's name ")
NO = input("Enter a funky noise ")
vengeance = input("What would be the best way to get revenge on someone ")
revengeance = input("What would that be as a verb ending in ing? ")
horrified = input("Enter the way you feel when watching horror movies ")
print(man + " " + walks + " into a Mcdonalds and orders " + quantity + food + "'s, then  discovers that " + manSus + " has killed his best friend, the very " + describer + " " + manFriend)
print(NO + " yelled " + man + ". " + man + " was " + horrified + " that someone could have done this" )
print("I vow to avenge " + manFriend + " by " + vengeance + ", swore " + man)
print("And so " + man + " did, by " + revengeance + " on " + manSus)